import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeProvider";

const ubuntu = Ubuntu({
  subsets: ['latin'], // Adjust subsets based on your needs
  weight: ["300", "400", "500", "700"], // Specify font weights
  variable: '--font-ubuntu', // Optional: Use a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ubuntu.variable}
      >
        <ThemeProvider>
          <main className="dark:bg-zinc-950 bg-white">
            <div className="h-[100dvh] w-full max-w-screen-2xl mx-auto">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html >
  );
}
