/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IButton {
        "classes": string;
        "color": 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger';
        "disableRipple": boolean;
        "disabled": boolean;
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "variant": 'solid' | 'outline' | 'light' | 'flat' | 'ghost' | 'shadow';
    }
    interface ISpinner {
        "color": 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | string;
        "emptyColor": string;
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "speed": string;
        "thickness": string;
    }
}
declare global {
    interface HTMLIButtonElement extends Components.IButton, HTMLStencilElement {
    }
    var HTMLIButtonElement: {
        prototype: HTMLIButtonElement;
        new (): HTMLIButtonElement;
    };
    interface HTMLISpinnerElement extends Components.ISpinner, HTMLStencilElement {
    }
    var HTMLISpinnerElement: {
        prototype: HTMLISpinnerElement;
        new (): HTMLISpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "i-button": HTMLIButtonElement;
        "i-spinner": HTMLISpinnerElement;
    }
}
declare namespace LocalJSX {
    interface IButton {
        "classes"?: string;
        "color"?: 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger';
        "disableRipple"?: boolean;
        "disabled"?: boolean;
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "variant"?: 'solid' | 'outline' | 'light' | 'flat' | 'ghost' | 'shadow';
    }
    interface ISpinner {
        "color"?: 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | string;
        "emptyColor"?: string;
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "speed"?: string;
        "thickness"?: string;
    }
    interface IntrinsicElements {
        "i-button": IButton;
        "i-spinner": ISpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "i-button": LocalJSX.IButton & JSXBase.HTMLAttributes<HTMLIButtonElement>;
            "i-spinner": LocalJSX.ISpinner & JSXBase.HTMLAttributes<HTMLISpinnerElement>;
        }
    }
}
