/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IButton {
        "color": 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger';
        "variant": 'solid' | 'outline' | 'light' | 'flat' | 'ghost' | 'shadow';
    }
}
declare global {
    interface HTMLIButtonElement extends Components.IButton, HTMLStencilElement {
    }
    var HTMLIButtonElement: {
        prototype: HTMLIButtonElement;
        new (): HTMLIButtonElement;
    };
    interface HTMLElementTagNameMap {
        "i-button": HTMLIButtonElement;
    }
}
declare namespace LocalJSX {
    interface IButton {
        "color"?: 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger';
        "variant"?: 'solid' | 'outline' | 'light' | 'flat' | 'ghost' | 'shadow';
    }
    interface IntrinsicElements {
        "i-button": IButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "i-button": LocalJSX.IButton & JSXBase.HTMLAttributes<HTMLIButtonElement>;
        }
    }
}
